SET CLASS_NAME=TaskB
SET LAB_NUM=jd01_05
SET TEST_NAME=Test_jd01_05

SET SRC_PATH=c:\java-lab\JD2021-02-24\src
SET OUTPUT_PATH=c:\java-lab\JD2021-02-24\classes
SET USER_PATH=by\it\dudko
SET USER_PACKAGE=by.it.dudko

javac -d %OUTPUT_PATH% %SRC_PATH%\%USER_PATH%\%LAB_NUM%\%CLASS_NAME%.java
java -cp lib.jar;%OUTPUT_PATH% %USER_PACKAGE%.%LAB_NUM%.%CLASS_NAME%

pause